version: '2.1'

volumes:
  luigid-data:
    driver: local

services:

  #
  # Luigi Service
  #

  luigid:
    build: .
    entrypoint: luigid
    volumes:
      - luigid-data:/luigi
      - ./config/luigi.cfg:/luigi/luigid.cfg
    environment:
      LUIGI_CONFIG_PATH: /luigi/luigid.cfg
    ports:
      - "0.0.0.0:8082:8082"
